name: Build asset on Linux (Android)

on: [push]

jobs:
  upload_asset_android:
    name: Upload Asset on Linux (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c

      - name: Run Buildscript
        run: sh ./build-on-linux-android.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-android
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0