name: Build asset on Linux

on: [push]

jobs:
  build_asset_linux:
    name: Build asset on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Buildscript
        run: sh ./build-on-linux.sh

