name: Build asset on Windows

on: [push]

jobs:
  build_asset_windows:
    name: Build asset on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
            vs-version: 17.0
            # vs-version: '[16.11, 16.12)'

      - name: Run Buildscript
        run: ./build-on-windows.bat