name: Build asset on macOS (XCFramework)

on: [push]

jobs:
  upload_asset_apple_xcframework:
    name: Upload Asset on macOS (xcframework)
    # runs-on: macos-latest
    runs-on: macos-13
    steps:
      - name: Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Dependency
        run: brew install coreutils automake

      - name: Run Buildscript
        run: sh ./build-on-mac-ios.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-apple-xcframework
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0