name: Release with Tag

on:
  push:
    tags:
      - '*'

jobs:
  ## ======================================================================================================
  upload_asset_windows:
    name: Upload Asset on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v5

      - name: Add msbuild to PATH
        # https://github.com/microsoft/setup-msbuild
        uses: microsoft/setup-msbuild@v2
        with:
            vs-version: 17.0
            # vs-version: '[16.11, 16.12)'

      - name: Run Buildscript
        shell: pwsh
        run: .\build-on-windows.ps1

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          path: libsodium/bin
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  ## ======================================================================================================
  upload_asset_linux:
    name: Upload Asset on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v5

      - name: Run Buildscript
        run: sh ./build-on-linux.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  ## ======================================================================================================
  upload_asset_android:
    name: Upload Asset on Linux (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c

      - name: Run Buildscript
        run: sh ./build-on-linux-android.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-android
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0


  ## ======================================================================================================
  upload_asset_macos:
    name: Upload Asset on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependency
        run: brew install coreutils automake

      - name: Run Buildscript
        run: sh ./build-on-mac.sh

      # - name: Print MD5
      #   run: 

      - name: Run Zip
        run: zip -r macos.zip output/*

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-macos
          path: macos.zip
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  ## ======================================================================================================
  upload_asset_apple_xcframework:
    name: Upload Asset on macOS (xcframework)
    # runs-on: macos-latest
    runs-on: macos-13
    steps:
      - name: Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Dependency
        run: brew install coreutils automake

      - name: Run Buildscript
        run: sh ./build-on-mac-ios.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-apple-xcframework
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  ## ======================================================================================================
  upload_asset_linux_wasm:
    name: Upload Asset on Linux (wasm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v5

      # https://github.com/mymindstorm/setup-emsdk
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: 'emsdk-cache'

      - name: Run Buildscript
        run: sh ./build-on-linux-wasm.sh

      - name: 🎁⏫ Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-wasm
          path: output
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  ## ======================================================================================================
  release:
    needs: [upload_asset_windows, upload_asset_linux, upload_asset_linux_wasm, upload_asset_android, upload_asset_macos, upload_asset_apple_xcframework]
    name: Write Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            CHANGELOG.md

      - name: Make Directory For Download Artifacts
        run: |
          mkdir -p download-artifacts

      - name: 🎁⏬ Download Artifact
         # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v5
        with:
          path: download-artifacts

      - name: 📦 Zip Artifacts
        run: |
          cd download-artifacts
          
          zip -r android.zip           artifact-android/
          zip -r wasm.zip              artifact-wasm/
          zip -r linux.zip             artifact-linux/
          zip -r windows.zip           artifact-windows/
          zip -r macos.zip             artifact-macos/
          zip -r apple-xcframework.zip artifact-apple-xcframework/

      - name: Log artifact download
        run: |
          ls -alh
          ls -alh download-artifacts
    
      - name: Get Tagname
        ## ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        ## echo "::set-output name={name}::{value}" (deprecated)
        ## echo "{name}={value}" >> $GITHUB_OUTPUT  (updated)
        id: tag_name
        run: |
          echo "current_version"="${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Changelog Reader
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: 🚀 Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          fail_on_unmatched_files: true
          files: |
            ./download-artifacts/android.zip
            ./download-artifacts/wasm.zip
            ./download-artifacts/linux.zip
            ./download-artifacts/windows.zip
            ./download-artifacts/macos.zip
            ./download-artifacts/apple-xcframework.zip